(defpackage #:urbit/tests/speed
  (:use #:cl #:fiveam #:named-readtables
        #:urbit/tests #:urbit/nock/ideal #:urbit/nock/world
        #:urbit/hoon/syntax #:urbit/nock/jets #:urbit/nock/axis))

(in-package #:urbit/tests/speed)
(in-readtable hoon)

(def-suite speed-tests
           :description "test the functions on (core) speed objects"
           :in all-tests)

(in-suite speed-tests)

(test valid
  (is (speed-valid :void))
  (is (speed-valid (make-assumption)))
  (let ((expired (make-assumption)))
    (setf (assumption-valid expired) nil)
    (is (not (speed-valid expired))))
  (bottle
    (let* ((root (ilit [[1 %foo] %foo]))
           (root-stencil (install-root-stencil %foo root 0)))
      (is (speed-valid root-stencil))
      (let* ((kid [[1 42] root])
             (kspd (get-speed kid)))
        (is (typep kspd 'mean))
        (is (speed-valid kspd))
        (let* ((kid-stencil (install-child-stencil
                              %kid (get-battery kid) 1 root-stencil 0))
               (kstop [[1 42] %no])
               (kss (get-speed kstop)))
          (is (typep kss 'stop))
          (is (speed-valid kss))
          (is (= 1 (stop-axis kss)))
          (is (not (speed-valid kspd)))
          (is (speed-valid kss))
          (setq kspd (get-speed kid))
          (is (typep kspd 'fast))
          (is (eq kspd kid-stencil)))
        (let* ((root2 (ilit [[1 %foo] %bar]))
               (rstop (ilit [[1 %foo] 0 0]))
               (r2spd (get-speed root2))
               (rss   (get-speed rstop))
               (kid2 [[1 42] root2])
               (k2spd (get-speed kid2)))
          (is (typep rss 'stop))
          (is (speed-valid rss))
          (is (= 1 (stop-axis rss)))
          (is (typep r2spd 'slug))
          (is (speed-valid r2spd))
          (is (typep k2spd 'slow))
          (is (speed-valid k2spd))
          (let ((root2-stencil (install-root-stencil %bar root2 0)))
            (is (not (speed-valid r2spd)))
            (setq r2spd (get-speed root2))
            (is (eq r2spd root2-stencil))
            (is (not (speed-valid k2spd)))
            (setq k2spd (get-speed kid2))
            (is (typep k2spd 'spry))
            (is (speed-valid k2spd))
            (is (speed-valid rss))
            (let ((k2-stencil (install-child-stencil
                                %kid2 (get-battery kid2) 1 root2-stencil 0)))
              (is (not (speed-valid k2spd)))
              (setq k2spd (get-speed kid2))
              (is (typep k2spd 'fast))
              (is (eq k2spd k2-stencil)))))))))

(defmacro for-all-axes ((axis len) &body forms)
  `(for-all ((,axis (gen-integer :min 2)))
     (let ((,len (axis-length ,axis)))
       ,@forms)))

(defun random-heads-yes (spd)
  (is (axle-changes-speed 2 1 spd))
  (is (not (axle-changes-speed 3 1 spd)))
  (for-all-axes (a l)
    (if (tax a)
        (is (not (axle-changes-speed a l spd)))
        (is (axle-changes-speed a l spd)))))

(test axle-changes-void
  (random-heads-yes :void))

(test axle-changes-mean
  (random-heads-yes (make-assumption)))

(test axle-changes-slug
  (let ((spd (make-slug (make-assumption))))
    (for-all-axes (a l)
      (is (axle-changes-speed a l spd)))))

(test axle-changes-stop
  (is (axle-changes-speed #b10 1 (make-stop #b110010101)))
  (is (axle-changes-speed #b100 2 (make-stop #b110010101)))
  (is (axle-changes-speed #b101 2 (make-stop #b110010101)))
  (is (not (axle-changes-speed #b110 2 (make-stop #b11))))
  (is (axle-changes-speed #b11 1 (make-stop #b1)))
  (is (axle-changes-speed #b11 1 (make-stop #b110)))
  (is (axle-changes-speed #b111 2 (make-stop #b11)))
  (is (axle-changes-speed #b11 1 (make-stop #b11))))

(defun ilit (literal)
  (find-ideal literal))

(test axle-changes-fast
  (bottle
    (let* ((root (ilit [[0 3] %rut]))
           (rsten (install-root-stencil %rut root 0)))
      (is (axle-changes-speed #b10 1 rsten))
      (is (axle-changes-speed #b11 1 rsten))
      (for-all-axes (a l)
        (is (axle-changes-speed a l rsten)))
      (let* ((bat (ilit [[0 6] 0 15]))
             (ksten (install-child-stencil %kid bat 3 rsten 0)))
        (is (axle-changes-speed #b10 1 ksten))
        (is (axle-changes-speed #b11 1 ksten))
        (is (not (axle-changes-speed #b110 2 ksten)))
        (is (not (axle-changes-speed #b1101 3 ksten)))
        (is (not (axle-changes-speed #b1100 3 ksten)))
        (is (not (axle-changes-speed #b11010 4 ksten)))
        (is (not (axle-changes-speed #b11011 4 ksten)))
        (is (axle-changes-speed #b111 2 ksten))
        (is (axle-changes-speed #b1111 3 ksten))
        (is (axle-changes-speed #b1110 3 ksten))
        (is (axle-changes-speed #b11110 4 ksten))
        (is (axle-changes-speed #b11111 4 ksten))))))

(test axle-changes-child
  (bottle
    (let* ((root1 (ilit [[0 3] %rid]))
           (root2 (ilit [[0 3] %rud]))
           (root3 (ilit [[0 3] %rad]))
           (rst1 (install-root-stencil %rid root1 0))
           (rst2 (install-root-stencil %rud root2 0))
           (bat (ilit [[0 6] 1 42]))
           (fast-cor [bat 0 root1])
           (fast-sten (install-child-stencil %fst bat 3 rst1 0))
           (fast-spd (get-speed fast-cor))
           (spry-cor [bat 0 root2])
           (spry-spd (get-speed spry-cor))
           (slow-cor [bat 0 root3])
           (slow-spd (get-speed slow-cor)))
      (declare (ignore rst2))
      (is (typep fast-spd 'fast))
      (is (eq fast-spd fast-sten))
      (is (typep spry-spd 'spry))
      (is (typep slow-spd 'slow))
      (is (axle-changes-speed #b10 1 spry-spd))
      (is (axle-changes-speed #b10 1 slow-spd))
      (is (axle-changes-speed #b101 2 spry-spd))
      (is (axle-changes-speed #b101 2 slow-spd))
      (is (not (axle-changes-speed #b110 2 slow-spd)))
      (is (not (axle-changes-speed #b110 2 spry-spd)))
      (is (not (axle-changes-speed #b1101 3 slow-spd)))
      (is (not (axle-changes-speed #b1101 3 spry-spd)))
      (is (not (axle-changes-speed #b1100 3 slow-spd)))
      (is (not (axle-changes-speed #b1100 3 spry-spd)))
      (is (axle-changes-speed #b111 2 spry-spd))
      (is (axle-changes-speed #b111 2 slow-spd))
      (is (axle-changes-speed #b1111 3 spry-spd))
      (is (axle-changes-speed #b1111 3 slow-spd))
      (is (axle-changes-speed #b1110 3 spry-spd))
      (is (axle-changes-speed #b1110 3 slow-spd)))))
